config/routes.rb
InyxCatalogRails::Engine.routes.draw do

	get '/catalogos', to: 'catalogs#catalog_index' if InyxCatalogRails::catalog_index
	get '/catalogos/:catalog_id/archivos', to: 'attachments#attachment_index' if InyxCatalogRails::attachment_index
	get '/catalogos/:catalog_id/archivos/:id', to: 'attachments#attachment_show' if InyxCatalogRails::attachment_show

  scope :admin do
	  resources :catalogs do
			resources :attachments do
				collection do
			  		post '/delete', to: 'attachments#delete'
			  	end
			end
			collection do
		  		post '/delete', to: 'catalogs#delete'
		  	end
		end
	end

end

app/models/inyx_catalog_rails/attachment.rb
module InyxCatalogRails
  class Attachment < ActiveRecord::Base
  	belongs_to :catalog
  	include Elasticsearch::Model
  	include Elasticsearch::Model::Callbacks
    mount_uploader :image, CoverUploader
    after_update :remove_image
    validates_presence_of :name
    before_save :url_iframe_service
    before_save :create_permalink

  	def as_json(options = {})
      {
        id: self.id,
        name: self.name,
        upload: self.upload,
        description: self.description,
        image: self.image.url,
        url: self.url,
        target: self.target,
        public_this: self.public ? "Publicado" : "No publicado",
        created_at: self.created_at.strftime("%d-%m-%Y"),
        catalog_id: self.catalog_id,
        permalink: self.permalink
      }
    end

    def create_permalink
      self.permalink=self.name.downcase.parameterize
    end

    def remove_image
      if !self.image_url.nil? and self.upload != "1"
        image = File.dirname(Rails.root.join("public"+self.image_url))
        FileUtils.rm_rf(image)
      end
    end

      #params[:search] is false
  	def self.index(current_user, catalog_id)
  		Attachment.where(catalog_id: catalog_id).order("created_at DESC")
  	end

  	#params[:search] is true
  	def self.index_search(objects, current_user, catalog_id)
  		objects.order("created_at DESC")
  	end

  	#params[:search] is true
  	def self.index_total(objects, current_user, catalog_id)
  		objects.count
  	end

    def self.multiple_destroy(ids, current_user)
      ids.each do |id|
        if !current_user.has_role? :admin
          raise CanCan::AccessDenied.new("Access Denied", :delete, InyxCatalogRails::Attachment)
        end
      end
      Attachment.destroy ids
    end

    def self.query(query)
	    { query: { multi_match:  { query: query, fields: [:name, :type, :description, :public_this, :created_at] , operator: :and }  }, sort: { id: "desc" }, size: Attachment.count }
	  end

    def url_iframe_service
      if !self.url.blank?
        video = self.detected_video_service
        begin
          case video.keys.first
            when "youtube"
              self.url="https://www.youtube.com/embed/"+video.values.first
            when "vimeo"
              self.url="https://player.vimeo.com/video/"+video.values.first
            when "soundcloud"
              detected_soundcloud_sets              
            when "imagen"
            else
              self.url=""
            end
        rescue
          self.url=""
        end
      end
    end

    def detected_soundcloud_sets
      client = Soundcloud.new(:client_id => 'YOUR_CLIENT_ID')
      begin
        track = client.get('/resolve', :url => self.url)
        if self.url.split(/\W+/).include?("sets")
          self.url="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/#{track.id}&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"
        else
          self.url="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/#{track.id}&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"
        end 
      rescue Soundcloud::ResponseError => e
        
      end
    end

    def detected_video_service
      ["youtube", "vimeo", "soundcloud"].each do |service|     
        return { service=>self.url.split(/\W+/).last } if self.url.split(/\W+/).include?(service)
      end
      if self.upload == "2"
        {"imagen"=>""}
      end
    end
    
  end
  Attachment.import
end

app/models/inyx_catalog_rails/catalog.rb
require 'elasticsearch/model'
module InyxCatalogRails
  class Catalog < ActiveRecord::Base		
  	include Elasticsearch::Model
  	include Elasticsearch::Model::Callbacks
  	has_many :attachments, :dependent => :destroy
    mount_uploader :cover, CoverUploader
    before_save :create_permalink


  	def as_json(options = {})
      {
        id: self.id,
        name: self.name,
        description: self.description,
        cover: self.cover.url,
        category: self.category,
        public_this: self.public ? "Publicado" : "No publicado",
        created_at: self.created_at.strftime("%d-%m-%Y"),        
        count_attachments: Attachment.where(catalog_id: self.id).count,
        permalink: self.permalink
      }
    end

    def create_permalink
      self.permalink=self.name.downcase.parameterize
    end

      #params[:search] is false
  	def self.index(current_user)
  		Catalog.order("created_at DESC")
  	end

  	#params[:search] is true
  	def self.index_search(objects, current_user)
  		objects.order("created_at DESC")
  	end

  	#params[:search] is true
  	def self.index_total(objects, current_user)
  		objects.count
  	end

    def self.multiple_destroy(ids, current_user)
      ids.each do |id|
        if !current_user.has_role? :admin
          raise CanCan::AccessDenied.new("Access Denied", :delete, InyxCatalogRails::Catalog)
        end
      end
      Catalog.destroy ids
    end

    def self.query(query)
	    { query: { multi_match:  { query: query, fields: [:name, :description, :category, :public_this, :created_at] , operator: :and }  }, sort: { id: "desc" }, size: Catalog.count }
	  end
    
  end
  Catalog.import
end

app/controllers/inyx_catalog_rails/application_controller.rb
module InyxCatalogRails
  class ApplicationController < ::ApplicationController
  end
end

app/controllers/inyx_catalog_rails/attachments_controller.rb
require_dependency "inyx_catalog_rails/application_controller"

module InyxCatalogRails
  class AttachmentsController < ApplicationController
    before_action :set_attachment, only: [:show, :edit, :update, :destroy]
    layout :resolve_layout
 
    def index      

      if params[:search].blank?
        @objects = Attachment.index(current_user, params[:catalog_id])
        @total_rows = @objects.count
        @objects = last_page(@objects, params[:currentPage].to_i) if @objects.count != 0
      else
        if(params[:direction]=="refresh")
          sleep(1)
        end
        items = Attachment.search(Attachment.query params[:search])
        @total_rows = Attachment.index_total items.records, current_user, params[:catalog_id]
        @objects = Attachment.index_search last_page_search(items, params[:currentPage].to_i).records, current_user, params[:catalog_id]
      end
      
      respond_to do |format|
        format.html { render action: 'index' }
        format.json { render :json => { objects: @objects, total_rows: @total_rows } }
      end
    end
    # GET /attachments/1
    def show
    end

    # GET /attachments/new
    def new
      @attachment = Attachment.new
    end

    # GET /attachments/1/edit
    def edit
    end

    # POST /attachments
    def create
      @attachment = Attachment.new(attachment_params)
      @attachment.catalog_id = params[:catalog_id]

      if @attachment.save
        redirect_to catalog_attachments_path, notice: 'Attachment was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /attachments/1
    def update
      if @attachment.update(attachment_params)
        @attachment.__elasticsearch__.index_document
        redirect_to catalog_attachments_path, notice: 'Attachment was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /attachments/1
    def destroy
      @attachment.destroy
      redirect_to catalog_attachments_path, notice: 'Attachment was successfully destroyed.'
    end

    def attachment_index
      @catalog = Catalog.find_by_id(params[:catalog_id]);
      @attachments = Attachment.where(:catalog_id=>params[:catalog_id])
    end

    def attachment_show
      @attachment = Attachment.find_by_id(params[:id])
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_attachment
        @attachment = Attachment.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def attachment_params
        params.require(:attachment).permit(:name, :upload, :description, :image, :url, :target, :public, :catalog_id)
      end

    def resolve_layout
      case action_name
        when "attachment_index", "attachment_show"
          "inyx_catalog_rails/frontend/application"
        else 
          "admin/application"
        end
      end
    
  end
end

app/controllers/inyx_catalog_rails/catalogs_controller.rb
require_dependency "inyx_catalog_rails/application_controller"

module InyxCatalogRails
  class CatalogsController < ApplicationController
    before_action :set_catalog, only: [:show, :edit, :update, :destroy]
    layout :resolve_layout
    # GET /catalogs
    
    # GET /catalogs/1
    def show
    end

    # GET /catalogs/new
    def new
      @catalog = Catalog.new
    end

    # GET /catalogs/1/edit
    def edit
    end

    # POST /catalogs
    def create
      @catalog = Catalog.new(catalog_params)

      if @catalog.save
        redirect_to catalogs_path, notice: 'Catalog was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /catalogs/1
    def update
      if @catalog.update(catalog_params)
        @catalog.__elasticsearch__.index_document
        redirect_to catalogs_path, notice: 'Catalog was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /catalogs/1
    def destroy
      @catalog.destroy
      redirect_to catalogs_url, notice: 'Catalogo ha sido borrado satisfactoriamente.'
    end

    def catalog_index
      @catalogs = Catalog.all
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_catalog
        @catalog = Catalog.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def catalog_params
        params.require(:catalog).permit(:name, :description, :cover, :category, :public)
      end

    def resolve_layout
      case action_name
        when "catalog_index"
          "inyx_catalog_rails/frontend/application"
        else 
          "admin/application"
        end
      end
    end

  end

app/helpers/inyx_catalog_rails/application_helper.rb
module InyxCatalogRails
  module ApplicationHelper
  end
end

app/helpers/inyx_catalog_rails/attachments_helper.rb
module InyxCatalogRails
  module AttachmentsHelper
  end
end

app/helpers/inyx_catalog_rails/catalogs_helper.rb
module InyxCatalogRails
  module CatalogsHelper
  end
end

app/views/inyx_catalog_rails/attachments/_form.html.haml
- (action_name == "new" or action_name == "create") ? action="create" : action="update"
= simple_form_for @attachment, :url => url_for(:action => action, :controller => 'attachments') do |f|
  .container_form 
    .title_form
      Datos de Archivo
    .form-inyx
      = f.input :name, label: false, input_html: { class: 'form-control input-inyx',placeholder: "Nombre" }

      #input-upload
        = f.input :upload, label: false, collection: [["Subir imagen", 1], ["Imagen por url", 2], ["Video por url", 3], ["Musica por url", 3]], include_blank: "- Tipo de Archivo -", input_html: { class: "form-control input-inyx" }

      = f.input :description, label: false, input_html: { class: 'form-control input-inyx',placeholder: "Descripción" }

      #url
        = f.input :url, label: false, input_html: { class: 'form-control input-inyx',placeholder: "Url" }
      #externo
        = f.input :target, label: false, input_html: { class: 'form-control input-inyx',placeholder: "Enlance Externo" }

      %br
      = f.input :image, label: false, as: :file, input_html: { class: "form-control file", placeholder: 'Imagen', "data-buttonBefore" => false, "data-input" => false, "data-buttonText" => params[:action] == "new" ? "Subir imágen" : "Cambiar imágen", id: "input-20" }
      
      = f.input :public, :wrapper => :inline_checkbox
     
    %br
    .panel-footer
      .form-actions
        = f.button :submit, "Guardar", class: "btn submit-inyx pull-right"
      .clearfix

:javascript
    $('#input-upload').on('change', '', function (e) {

      var valueSelected = $("#input-upload option:selected").val();

      if(valueSelected=="1"){
        $(".file").show();
        $("#url").hide();
        $("#externo").show();
      }else if(valueSelected=="2"){
        $(".file").hide();
        $("#url").show();
        $("#externo").show();
      }else{
        $(".file").hide();
        $("#url").show();
        $("#externo").hide();
      }
    });


-if @attachment.upload == "1"
  :javascript    
    $(".file").show();
    $("#url").hide();
-else
  - if @attachment.upload.blank?
    :javascript    
      $(".file").hide();
      $("#url").hide();
  -else
    :javascript    
      $(".file").hide();
      $("#url").show();



- if @attachment.image.blank?
  :javascript
    $("#input-20").fileinput({
      browseClass: "btn btn-primary btn-block",
      showCaption: false,
      showRemove: false,
      showUpload: false,
      browseIcon: '<i class="fa fa-folder-open"></i>',
      browseLabel: ' Subir imágen',
    });
- else 
  :javascript
    $("#input-20").fileinput({
      browseClass: "btn btn-primary btn-block",
      showCaption: true,
      captionIcon: '<i class="fa fa-folder-open"></i>',
      showRemove: false,
      showUpload: false,
      browseIcon: '<i class="fa fa-folder-open"></i>',
      browseLabel: ' Subir imágen',
      initialPreview: ['"#{image_tag @attachment.image, class: 'file-preview-image' if !@attachment.image.blank?}"'],
      initialCaption: " #{@attachment.image.file.filename.humanize}"
    });

app/views/inyx_catalog_rails/attachments/_view_lg_md.html.haml
%div{ 'ng-init'=>"init(#{@objects.to_json}, '/admin/catalogs/#{params[:catalog_id]}/attachments', '#{params[:search]}', #{@total_rows}, #{Kaminari.config.default_per_page})", "resize" => "" }
  .grid-content
    .col-lg-9.col-md-9{ style: "padding:0px;" } 
      .list-wrapper
        .panel.panel-default
          - flash.each do |name, msg|
            - if msg.is_a?(String)
              %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'} pull-right", id: "message_alerts"}
                %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
                = content_tag :div, msg, :id => "flash_#{name}"
          .panel-heading#list-heading
            = link_to catalogs_path, title: "Ir atrás", class: "btn btn-default btn-action" do
              %i.fa.fa-arrow-left
            - if can? :new, InyxCatalogRails::Attachment
              = link_to new_catalog_attachment_path, title: t("admin.buttons.new"), class: "btn btn-default btn-action" do
                %i.fa.fa-plus
            %a.btn.btn-default.btn-action{"ng-click" => "refresh()", "ng-disabled" => "pagesItemsSelected[currentPageServer].length != 0", :title => t("admin.buttons.refresh") }
              %i.fa.fa-refresh#icon-refresh{'ng-show'=>"!loadingRefresh"}
              %i.fa.fa-refresh.fa-spin{'ng-show'=>"loadingRefresh"}
            - if can? :delete, InyxCatalogRails::Attachment
              %a.btn.btn-default.btn-action{"ng-show" => "objects.length", "ng-click" => "allSelected(objects)", :title => t("admin.buttons.select_all") }
                %i.fa.fa-square-o{"ng-show" => "!btnDelete"}
                %i.fa.fa-check-square-o{ "ng-show" => "btnDelete" } 
              %a.btn.btn-default.btn-action#btn-delete{ "ng-show" => "btnDelete", "ng-click" => "destroy('¿Estas seguro de querer eliminar los catalogos seleccionados?')", :title => t("admin.buttons.trash") }
                %i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingDelete" }
                %i.fa.fa-trash-o{ 'ng-show' => "!loadingDelete" }
            .paginator.pull-right{ "ng-show" => "objects.length > 0"}
              %button.btn.btn-default.pull-right.hidden-xs{'disabled'=>"", style:"color:#000; margin-left:3px;"}
                Página {{currentPage+1}} de {{numberOfPages()}}
              %a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
                %i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
                %i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
              %a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
                %i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
                %i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
          .panel-body{ style: "border-right: 1px solid #e7e7e7;" }
            = @object
            #table-scroll
              %table.grid{style: "width:100%"}
                %tbody
                  %tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object)", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
                    - if can? :delete, InyxCatalogRails::Attachment
                      %td{ width: "1px;" }
                        .checkboxFour
                          %input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
                          %label{ for: "check-{{object.id}}" }
                            %span
                    %td {{ object.name }}
                    %td {{ object.public_this }}
                  %tr{"ng-show" => "!objects.length"}
                    %td{:style => "width:100%"}
                      %center
                        %i.fa.fa-frown-o
                        No hay archivos.
      
    .col-lg-3.col-md-3{ style: "padding:0px;"}
      .show-wrapper
        .show-head
        .show-body
          .panel.panel-default
            .panel-heading{ style: "height:55px;" }
              .actions{ "ng-show" => "object_data" }
                .title.pull-left{ style: "margin-top:6px;" }
                  %i.fa.fa-user
                  Archivo - {{ object_data.id }}
                - if can? :destroy, InyxCatalogRails::Attachment
                  = link_to "{{destroy_path(object_data.id)}}", title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar este catalogo?' }, class: "btn btn-default btn-action pull-right", "ng-show" => "object_data" do
                    %i.fa.fa-remove
                - if can? :edit, InyxCatalogRails::Attachment
                  = link_to "{{edit_path(object_data.id)}}", title: t('admin.actions.edit'), class: "btn btn-default btn-action pull-right", "ng-show" => "object_data", style: "margin-right:3px;" do
                    %i.fa.fa-pencil                
              .actions{ "ng-show" => "!object_data", style: "margin-top:6px;" }
                %i.fa.fa-user
                Archivo
            .panel-body
              .data{ style: "height: {{windowHeight-104}}px;", 'ng-controller'=>"iframeCtrl" }
                %img{ "ng-if" => "object_data.image && object_data.upload=='1'", "ng-src" => "{{object_data.image}}"}
                %img{ "ng-if" => "object_data.url && object_data.upload=='2'", "ng-src" => "{{object_data.url}}"}
                %div{ "ng-if" => "object_data.url && object_data.upload=='3'"}
                  %iframe.video-player.img-responsive{:allowfullscreen => "", :frameborder => "0",:src =>'{{iframe_url(object_data.url)}}'}
                .attributes{ "ng-show" => "object_data" }
                  %label Nombre: 
                  {{object_data.name}}
                  %br
                  %label Descripción: 
                  {{object_data.description}}
                  %br/
                  %label Fecha de creación:
                  {{object_data.created_at}}
                  %br/
                  %label Publicar:
                  {{object_data.public_this}}
                  %br/
                  %label{"ng-if" => "object_data.target"} Enlace externo:
                  %a{href: "{{object_data.target}}", "ng-if" => "object_data.target"}
                    {{object_data.target}}
                      
                  %br/
                .attributes{ "ng-show" => "!object_data"}
                  %center
                    No se ha seleccionado un archivos para mostrar.
        .show-footer

app/views/inyx_catalog_rails/attachments/_view_sm_xs.html.haml
- if can? :new, User
	= link_to new_catalog_attachment_path, class: "float-button" do
		%i.fa.fa-plus
.panel.panel-default{style:"margin-top:50px"}
	.panel-header
		.paginator{ "ng-show" => "objects.length > 0"}
			%center
				Página {{currentPage+1}} de {{numberOfPages()}}
			%a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
				%i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
			%a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
				%i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
	.panel-body#grid{ style: "border-right: 1px solid #e7e7e7;padding-left: 0px;padding-right: 0px;border-top-width: 36px;" }	
		%table.grid{style: "width:100%;"}
			%tbody
				%tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object);read(object);", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
					- if can? :delete, InyxCatalogRails::Attachment 
						%td{ width: "1px;" }
							.checkboxFour
								%input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
								%label{ for: "check-{{object.id}}" }
									%span
					%td
						= link_to "/admin/catalogs/{{object.catalog_id}}/attachments/{{object.id}}", style: "width:100%;" do
							{{ object.name }}
					%td 
						= link_to "/admin/catalogs/{{object.catalog_id}}/attachments/{{object.id}}", style: "width:100%;" do
							{{ object.public_this}}
					%td
						= link_to "/admin/catalogs/{{object.id}}/attachments", style: "width:100%;" do
							%i.fa.fa-check-circle-o{'ng-show'=>"object.public_this=='Publicado'"}
							%i.fa.fa-times-circle-o{'ng-show'=>"object.public_this=='No publicado'"}
				%tr{"ng-show" => "!objects.length"}
					%td{:style => "width:100%"}
						%center
							%i.fa.fa-frown-o
							No hay archivos.

app/views/inyx_catalog_rails/attachments/attachment_index.html.haml
.catalog.container	
	.jumbotron
		%h1 
			=@catalog.name
		%p{aling:"justify"}
			=@catalog.description
	.row
		- @attachments.each do |attachment| 
			-if attachment.public == true
				.col-sm-6.col-md-4
					- if attachment.target.blank?
						%a{:href => "/catalogos/#{attachment.catalog_id}/archivos/#{attachment.id}"}
							.thumbnail
								- if attachment.image && attachment.upload=='1'
									%img{src:"#{attachment.image}"}
								- if attachment.url && attachment.upload=='2'
									%img{src:"#{attachment.url}"}		
								- if attachment.url && attachment.upload=='3'
									%iframe.video-player.img-responsive{:allowfullscreen => "", :frameborder => "0",:src =>"#{attachment.url}"}
								.caption
									%h3 
										= attachment.name					
					- else 	
						%a{:href => "#{attachment.target}"}
							.thumbnail
								- if attachment.image && attachment.upload=='1'
									%img{src:"#{attachment.image}"}
								- if attachment.url && attachment.upload=='2'
									%img{src:"#{attachment.url}"}		
								- if attachment.url && attachment.upload=='3'
									%iframe.video-player.img-responsive{:allowfullscreen => "", :frameborder => "0",:src =>"#{attachment.url}"}
								.caption
									%h3 
										= attachment.name	

app/views/inyx_catalog_rails/attachments/attachment_show.html.haml
.catalog.container	
	.jumbotron
		- if @attachment.image && @attachment.upload=='1'
			%img{src:"#{@attachment.image}"}
		- if @attachment.url && @attachment.upload=='2'
			%img{src:"#{@attachment.url}"}		
		- if @attachment.url && @attachment.upload=='3'
			%iframe.video-player.img-responsive{:allowfullscreen => "", style:"height:500px;",:frameborder => "0",:src =>"#{@attachment.url}"}
		%h1 
			=@attachment.name
		%p{aling:"justify"}
			%b Descripcion:
			=@attachment.description
		%p{aling:"justify"}
			%b Fecha de creación:
			=@attachment.created_at

app/views/inyx_catalog_rails/attachments/edit.html.haml
= content_for(:title, "Admin - Archivos | Nuevo")

%div{ style: "padding:10px; padding-bottom:0px;"}
	= render 'form'

app/views/inyx_catalog_rails/attachments/index.html.haml
= content_for(:title, "Admin - Catálogos")

.view-lg-md.hidden-xs.hidden-sm
  = render "view_lg_md"
.view-sm-xs.hidden-lg.hidden-md
  = render "view_sm_xs"

app/views/inyx_catalog_rails/attachments/new.html.haml
= content_for(:title, "Admin - Archivos | Nuevo")

%div{ style: "padding:10px; padding-bottom:0px;"}
	= render 'form'

app/views/inyx_catalog_rails/attachments/show.html.haml
= content_for(:title, "Admin - Usuarios | #{@attachment.name}")
- flash.each do |name, msg|
	- if msg.is_a?(String)
		%div.hidden-xs{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", id:"message_alerts"}
			%button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
			= content_tag :div, msg, :id => "flash_#{name}"
%div
	.panel.panel-default{style:"margin-top:50px"}
		.panel-heading#heading-show{style:"padding-top:5px"}
			.actions
				.title.pull-left{ style: "margin-top:8px;" }
					%i.fa.fa-user
					Catálogo - 
					= @attachment.id
				- if can? :destroy, User
					= link_to catalog_path(@attachment), title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar este usuario?' }, class: "btn btn-default btn-action pull-right" do
						%i.fa.fa-remove
				- if can? :edit, User
					= link_to  edit_catalog_path(@attachment), title: t('admin.actions.edit'), class: "btn btn-default btn-action pull-right", style: "margin-right:3px;" do
						%i.fa.fa-pencil
		- if @attachment.image && @attachment.upload=='1'
			%img{src:"#{@attachment.image}"}
		- if @attachment.url && @attachment.upload=='2'
			%img{src:"#{@attachment.url}"}		
		- if @attachment.url && @attachment.upload=='3'
			%iframe.video-player.img-responsive{:allowfullscreen => "", :frameborder => "0",:src =>"#{@attachment.url}"}
		.panel-body#body-show
			%label= t('attachment.name')+': '
			= @attachment.name
			%br/
			%label= t('attachment.description')+': '
			= @attachment.description
			%br/
			%label= t('attachment.enlace_externo')+': '
			= @attachment.target
			%br/
			%label= t('attachment.fecha')+': '
			= @attachment.created_at.strftime("%d-%m-%Y")
			%br/
			%label= t('attachment.publicacion')+': '
			= @attachment.public ? "Publicado" : "No publicado"
			%br/